// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createCalendarEvent = `-- name: CreateCalendarEvent :one
INSERT INTO calendar_events (
  id, user_id, title, description, target_audience, start_time, end_time, is_full_day, repeat_type
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, user_id, title, description, target_audience, start_time, end_time, is_full_day, repeat_type, created_at, updated_at
`

type CreateCalendarEventParams struct {
	ID             string
	UserID         string
	Title          string
	Description    sql.NullString
	TargetAudience string
	StartTime      time.Time
	EndTime        time.Time
	IsFullDay      bool
	RepeatType     string
}

func (q *Queries) CreateCalendarEvent(ctx context.Context, arg CreateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, createCalendarEvent,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.TargetAudience,
		arg.StartTime,
		arg.EndTime,
		arg.IsFullDay,
		arg.RepeatType,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.TargetAudience,
		&i.StartTime,
		&i.EndTime,
		&i.IsFullDay,
		&i.RepeatType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCalendarEvent = `-- name: DeleteCalendarEvent :exec
DELETE FROM calendar_events
WHERE id = ?
`

func (q *Queries) DeleteCalendarEvent(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCalendarEvent, id)
	return err
}

const getCalendarEvent = `-- name: GetCalendarEvent :one
SELECT id, user_id, title, description, target_audience, start_time, end_time, is_full_day, repeat_type, created_at, updated_at FROM calendar_events
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCalendarEvent(ctx context.Context, id string) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, getCalendarEvent, id)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.TargetAudience,
		&i.StartTime,
		&i.EndTime,
		&i.IsFullDay,
		&i.RepeatType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCalendarEventsMonth = `-- name: ListCalendarEventsMonth :many
SELECT id, user_id, title, description, target_audience, start_time, end_time, is_full_day, repeat_type, created_at, updated_at FROM calendar_events
WHERE user_id = ? 
  AND (target_audience = ? OR ? = 'General')
  AND start_time >= ? 
  AND start_time <= ?
ORDER BY start_time ASC
`

type ListCalendarEventsMonthParams struct {
	UserID         string
	TargetAudience string
	Column3        interface{}
	StartTime      time.Time
	StartTime_2    time.Time
}

func (q *Queries) ListCalendarEventsMonth(ctx context.Context, arg ListCalendarEventsMonthParams) ([]CalendarEvent, error) {
	rows, err := q.db.QueryContext(ctx, listCalendarEventsMonth,
		arg.UserID,
		arg.TargetAudience,
		arg.Column3,
		arg.StartTime,
		arg.StartTime_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalendarEvent
	for rows.Next() {
		var i CalendarEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.TargetAudience,
			&i.StartTime,
			&i.EndTime,
			&i.IsFullDay,
			&i.RepeatType,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCalendarEvent = `-- name: UpdateCalendarEvent :one
UPDATE calendar_events
SET title = coalesce(?2, title),
    description = coalesce(?3, description),
    target_audience = coalesce(?4, target_audience),
    start_time = coalesce(?5, start_time),
    end_time = coalesce(?6, end_time),
    is_full_day = coalesce(?7, is_full_day),
    repeat_type = coalesce(?8, repeat_type),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, user_id, title, description, target_audience, start_time, end_time, is_full_day, repeat_type, created_at, updated_at
`

type UpdateCalendarEventParams struct {
	Title          sql.NullString
	Description    sql.NullString
	TargetAudience sql.NullString
	StartTime      sql.NullTime
	EndTime        sql.NullTime
	IsFullDay      sql.NullBool
	RepeatType     sql.NullString
	ID             string
}

func (q *Queries) UpdateCalendarEvent(ctx context.Context, arg UpdateCalendarEventParams) (CalendarEvent, error) {
	row := q.db.QueryRowContext(ctx, updateCalendarEvent,
		arg.Title,
		arg.Description,
		arg.TargetAudience,
		arg.StartTime,
		arg.EndTime,
		arg.IsFullDay,
		arg.RepeatType,
		arg.ID,
	)
	var i CalendarEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.TargetAudience,
		&i.StartTime,
		&i.EndTime,
		&i.IsFullDay,
		&i.RepeatType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
