// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finance.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createFinance = `-- name: CreateFinance :one
INSERT INTO finances (
  id, type, amount, topic, mode, target_audience, month, year, author_id, date
) VALUES (
  ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, type, amount, topic, mode, target_audience, month, year, author_id, date, created_at, updated_at
`

type CreateFinanceParams struct {
	ID             string
	Type           string
	Amount         float64
	Topic          string
	Mode           string
	TargetAudience string
	Month          sql.NullInt64
	Year           sql.NullInt64
	AuthorID       string
	Date           time.Time
}

func (q *Queries) CreateFinance(ctx context.Context, arg CreateFinanceParams) (Finance, error) {
	row := q.db.QueryRowContext(ctx, createFinance,
		arg.ID,
		arg.Type,
		arg.Amount,
		arg.Topic,
		arg.Mode,
		arg.TargetAudience,
		arg.Month,
		arg.Year,
		arg.AuthorID,
		arg.Date,
	)
	var i Finance
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Amount,
		&i.Topic,
		&i.Mode,
		&i.TargetAudience,
		&i.Month,
		&i.Year,
		&i.AuthorID,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFinance = `-- name: DeleteFinance :exec
DELETE FROM finances
WHERE id = ?
`

func (q *Queries) DeleteFinance(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteFinance, id)
	return err
}

const getFinance = `-- name: GetFinance :one
SELECT id, type, amount, topic, mode, target_audience, month, year, author_id, date, created_at, updated_at FROM finances
WHERE id = ? LIMIT 1
`

func (q *Queries) GetFinance(ctx context.Context, id string) (Finance, error) {
	row := q.db.QueryRowContext(ctx, getFinance, id)
	var i Finance
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Amount,
		&i.Topic,
		&i.Mode,
		&i.TargetAudience,
		&i.Month,
		&i.Year,
		&i.AuthorID,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listHistoryFinances = `-- name: ListHistoryFinances :many
SELECT id, type, amount, topic, mode, target_audience, month, year, author_id, date, created_at, updated_at FROM finances
WHERE mode = 'history' AND (target_audience = ? OR ? = 'General')
ORDER BY date DESC
`

type ListHistoryFinancesParams struct {
	TargetAudience string
	Column2        interface{}
}

func (q *Queries) ListHistoryFinances(ctx context.Context, arg ListHistoryFinancesParams) ([]Finance, error) {
	rows, err := q.db.QueryContext(ctx, listHistoryFinances, arg.TargetAudience, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finance
	for rows.Next() {
		var i Finance
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Amount,
			&i.Topic,
			&i.Mode,
			&i.TargetAudience,
			&i.Month,
			&i.Year,
			&i.AuthorID,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlannedFinances = `-- name: ListPlannedFinances :many
SELECT id, type, amount, topic, mode, target_audience, month, year, author_id, date, created_at, updated_at FROM finances
WHERE mode = 'planned' 
  AND year = ? 
  AND month = ?
  AND (target_audience = ? OR ? = 'General')
ORDER BY created_at DESC
`

type ListPlannedFinancesParams struct {
	Year           sql.NullInt64
	Month          sql.NullInt64
	TargetAudience string
	Column4        interface{}
}

func (q *Queries) ListPlannedFinances(ctx context.Context, arg ListPlannedFinancesParams) ([]Finance, error) {
	rows, err := q.db.QueryContext(ctx, listPlannedFinances,
		arg.Year,
		arg.Month,
		arg.TargetAudience,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Finance
	for rows.Next() {
		var i Finance
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Amount,
			&i.Topic,
			&i.Mode,
			&i.TargetAudience,
			&i.Month,
			&i.Year,
			&i.AuthorID,
			&i.Date,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateFinance = `-- name: UpdateFinance :one
UPDATE finances
SET type = coalesce(?2, type),
    amount = coalesce(?3, amount),
    topic = coalesce(?4, topic),
    mode = coalesce(?5, mode),
    target_audience = coalesce(?6, target_audience),
    month = coalesce(?7, month),
    year = coalesce(?8, year),
    date = coalesce(?9, date),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, type, amount, topic, mode, target_audience, month, year, author_id, date, created_at, updated_at
`

type UpdateFinanceParams struct {
	Type           sql.NullString
	Amount         sql.NullFloat64
	Topic          sql.NullString
	Mode           sql.NullString
	TargetAudience sql.NullString
	Month          sql.NullInt64
	Year           sql.NullInt64
	Date           sql.NullTime
	ID             string
}

func (q *Queries) UpdateFinance(ctx context.Context, arg UpdateFinanceParams) (Finance, error) {
	row := q.db.QueryRowContext(ctx, updateFinance,
		arg.Type,
		arg.Amount,
		arg.Topic,
		arg.Mode,
		arg.TargetAudience,
		arg.Month,
		arg.Year,
		arg.Date,
		arg.ID,
	)
	var i Finance
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Amount,
		&i.Topic,
		&i.Mode,
		&i.TargetAudience,
		&i.Month,
		&i.Year,
		&i.AuthorID,
		&i.Date,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
