// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: goal.sql

package db

import (
	"context"
	"database/sql"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (
  id, title, description, priority, target_audience, author_id
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, title, description, priority, target_audience, author_id, created_at, updated_at
`

type CreateGoalParams struct {
	ID             string
	Title          string
	Description    sql.NullString
	Priority       string
	TargetAudience string
	AuthorID       string
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, createGoal,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.TargetAudience,
		arg.AuthorID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.TargetAudience,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGoal = `-- name: DeleteGoal :exec
DELETE FROM goals
WHERE id = ?
`

func (q *Queries) DeleteGoal(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteGoal, id)
	return err
}

const getGoal = `-- name: GetGoal :one
SELECT id, title, description, priority, target_audience, author_id, created_at, updated_at FROM goals
WHERE id = ? LIMIT 1
`

func (q *Queries) GetGoal(ctx context.Context, id string) (Goal, error) {
	row := q.db.QueryRowContext(ctx, getGoal, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.TargetAudience,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGoals = `-- name: ListGoals :many
SELECT id, title, description, priority, target_audience, author_id, created_at, updated_at FROM goals
WHERE target_audience = ? OR ? = 'General'
ORDER BY created_at DESC
`

type ListGoalsParams struct {
	TargetAudience string
	Column2        interface{}
}

func (q *Queries) ListGoals(ctx context.Context, arg ListGoalsParams) ([]Goal, error) {
	rows, err := q.db.QueryContext(ctx, listGoals, arg.TargetAudience, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.TargetAudience,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET title = coalesce(?2, title),
    description = coalesce(?3, description),
    priority = coalesce(?4, priority),
    target_audience = coalesce(?5, target_audience),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, description, priority, target_audience, author_id, created_at, updated_at
`

type UpdateGoalParams struct {
	Title          sql.NullString
	Description    sql.NullString
	Priority       sql.NullString
	TargetAudience sql.NullString
	ID             string
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRowContext(ctx, updateGoal,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.TargetAudience,
		arg.ID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.TargetAudience,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
