// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Admin struct {
	ID           int64
	Username     string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type CalendarEvent struct {
	ID             string
	UserID         string
	Title          string
	Description    sql.NullString
	TargetAudience string
	StartTime      time.Time
	EndTime        time.Time
	IsFullDay      bool
	RepeatType     string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Finance struct {
	ID             string
	Type           string
	Amount         float64
	Topic          string
	Mode           string
	TargetAudience string
	Month          sql.NullInt64
	Year           sql.NullInt64
	AuthorID       string
	Date           time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Goal struct {
	ID             string
	Title          string
	Description    sql.NullString
	Priority       string
	TargetAudience string
	AuthorID       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Note struct {
	ID             string
	Title          string
	Description    sql.NullString
	TargetAudience string
	AuthorID       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Partner struct {
	ID        string
	UserID1   string
	UserID2   string
	CreatedAt time.Time
}

type Promise struct {
	ID             string
	Title          string
	Description    sql.NullString
	Priority       string
	TargetAudience string
	AuthorID       string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Setting struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	Theme     string    `json:"theme"`
	AvatarUrl string    `json:"avatar_url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type SocialBattery struct {
	ID             string
	Level          int64
	TargetAudience string
	AuthorID       string
	UpdatedAt      time.Time
}

type Task struct {
	ID          string
	Title       string
	Description sql.NullString
	Status      string
	Priority    string
	AssigneeID  sql.NullString
	AuthorID    string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	Username     string    `json:"username"`
	PasswordHash string    `json:"-"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
