// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: note.sql

package db

import (
	"context"
	"database/sql"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (
  id, title, description, target_audience, author_id
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, title, description, target_audience, author_id, created_at, updated_at
`

type CreateNoteParams struct {
	ID             string
	Title          string
	Description    sql.NullString
	TargetAudience string
	AuthorID       string
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, createNote,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.TargetAudience,
		arg.AuthorID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TargetAudience,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNote = `-- name: DeleteNote :exec
DELETE FROM notes
WHERE id = ?
`

func (q *Queries) DeleteNote(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNote, id)
	return err
}

const getNote = `-- name: GetNote :one
SELECT id, title, description, target_audience, author_id, created_at, updated_at FROM notes
WHERE id = ? LIMIT 1
`

func (q *Queries) GetNote(ctx context.Context, id string) (Note, error) {
	row := q.db.QueryRowContext(ctx, getNote, id)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TargetAudience,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotes = `-- name: ListNotes :many
SELECT id, title, description, target_audience, author_id, created_at, updated_at FROM notes
WHERE target_audience = ? OR ? = 'General'
ORDER BY created_at DESC
`

type ListNotesParams struct {
	TargetAudience string
	Column2        interface{}
}

func (q *Queries) ListNotes(ctx context.Context, arg ListNotesParams) ([]Note, error) {
	rows, err := q.db.QueryContext(ctx, listNotes, arg.TargetAudience, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Note
	for rows.Next() {
		var i Note
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.TargetAudience,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes
SET title = coalesce(?2, title),
    description = coalesce(?3, description),
    target_audience = coalesce(?4, target_audience),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, description, target_audience, author_id, created_at, updated_at
`

type UpdateNoteParams struct {
	Title          sql.NullString
	Description    sql.NullString
	TargetAudience sql.NullString
	ID             string
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRowContext(ctx, updateNote,
		arg.Title,
		arg.Description,
		arg.TargetAudience,
		arg.ID,
	)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.TargetAudience,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
