// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: partner.sql

package db

import (
	"context"
)

const createPartner = `-- name: CreatePartner :one
INSERT INTO partners (
  id, user_id_1, user_id_2
) VALUES (
  ?, ?, ?
)
RETURNING id, user_id_1, user_id_2, created_at
`

type CreatePartnerParams struct {
	ID      string
	UserID1 string
	UserID2 string
}

func (q *Queries) CreatePartner(ctx context.Context, arg CreatePartnerParams) (Partner, error) {
	row := q.db.QueryRowContext(ctx, createPartner, arg.ID, arg.UserID1, arg.UserID2)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.UserID1,
		&i.UserID2,
		&i.CreatedAt,
	)
	return i, err
}

const deletePartner = `-- name: DeletePartner :exec
DELETE FROM partners
WHERE id = ?
`

func (q *Queries) DeletePartner(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePartner, id)
	return err
}

const getPartnerByUserID = `-- name: GetPartnerByUserID :one
SELECT id, user_id_1, user_id_2, created_at FROM partners
WHERE user_id_1 = ? OR user_id_2 = ? LIMIT 1
`

type GetPartnerByUserIDParams struct {
	UserID1 string
	UserID2 string
}

func (q *Queries) GetPartnerByUserID(ctx context.Context, arg GetPartnerByUserIDParams) (Partner, error) {
	row := q.db.QueryRowContext(ctx, getPartnerByUserID, arg.UserID1, arg.UserID2)
	var i Partner
	err := row.Scan(
		&i.ID,
		&i.UserID1,
		&i.UserID2,
		&i.CreatedAt,
	)
	return i, err
}
