// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: promise.sql

package db

import (
	"context"
	"database/sql"
)

const createPromise = `-- name: CreatePromise :one
INSERT INTO promises (
  id, title, description, priority, target_audience, author_id
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, title, description, priority, target_audience, author_id, created_at, updated_at
`

type CreatePromiseParams struct {
	ID             string
	Title          string
	Description    sql.NullString
	Priority       string
	TargetAudience string
	AuthorID       string
}

func (q *Queries) CreatePromise(ctx context.Context, arg CreatePromiseParams) (Promise, error) {
	row := q.db.QueryRowContext(ctx, createPromise,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.TargetAudience,
		arg.AuthorID,
	)
	var i Promise
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.TargetAudience,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePromise = `-- name: DeletePromise :exec
DELETE FROM promises
WHERE id = ?
`

func (q *Queries) DeletePromise(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deletePromise, id)
	return err
}

const getPromise = `-- name: GetPromise :one
SELECT id, title, description, priority, target_audience, author_id, created_at, updated_at FROM promises
WHERE id = ? LIMIT 1
`

func (q *Queries) GetPromise(ctx context.Context, id string) (Promise, error) {
	row := q.db.QueryRowContext(ctx, getPromise, id)
	var i Promise
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.TargetAudience,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPromises = `-- name: ListPromises :many
SELECT id, title, description, priority, target_audience, author_id, created_at, updated_at FROM promises
WHERE target_audience = ? OR ? = 'General'
ORDER BY created_at DESC
`

type ListPromisesParams struct {
	TargetAudience string
	Column2        interface{}
}

func (q *Queries) ListPromises(ctx context.Context, arg ListPromisesParams) ([]Promise, error) {
	rows, err := q.db.QueryContext(ctx, listPromises, arg.TargetAudience, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Promise
	for rows.Next() {
		var i Promise
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Priority,
			&i.TargetAudience,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePromise = `-- name: UpdatePromise :one
UPDATE promises
SET title = coalesce(?2, title),
    description = coalesce(?3, description),
    priority = coalesce(?4, priority),
    target_audience = coalesce(?5, target_audience),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, title, description, priority, target_audience, author_id, created_at, updated_at
`

type UpdatePromiseParams struct {
	Title          sql.NullString
	Description    sql.NullString
	Priority       sql.NullString
	TargetAudience sql.NullString
	ID             string
}

func (q *Queries) UpdatePromise(ctx context.Context, arg UpdatePromiseParams) (Promise, error) {
	row := q.db.QueryRowContext(ctx, updatePromise,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.TargetAudience,
		arg.ID,
	)
	var i Promise
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Priority,
		&i.TargetAudience,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
