// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package db

import (
	"context"
)

const getSettingsByUserID = `-- name: GetSettingsByUserID :one
SELECT id, user_id, theme, avatar_url, created_at, updated_at FROM settings WHERE user_id = ? LIMIT 1
`

func (q *Queries) GetSettingsByUserID(ctx context.Context, userID string) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettingsByUserID, userID)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSettings = `-- name: UpsertSettings :one
INSERT INTO settings (id, user_id, theme, avatar_url)
VALUES (?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    theme = excluded.theme,
    avatar_url = excluded.avatar_url,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, user_id, theme, avatar_url, created_at, updated_at
`

type UpsertSettingsParams struct {
	ID        string
	UserID    string
	Theme     string
	AvatarUrl string
}

func (q *Queries) UpsertSettings(ctx context.Context, arg UpsertSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, upsertSettings,
		arg.ID,
		arg.UserID,
		arg.Theme,
		arg.AvatarUrl,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Theme,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
