// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social_battery.sql

package db

import (
	"context"
)

const getSocialBattery = `-- name: GetSocialBattery :one
SELECT id, level, target_audience, author_id, updated_at FROM social_batteries
WHERE target_audience = ? LIMIT 1
`

func (q *Queries) GetSocialBattery(ctx context.Context, targetAudience string) (SocialBattery, error) {
	row := q.db.QueryRowContext(ctx, getSocialBattery, targetAudience)
	var i SocialBattery
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.TargetAudience,
		&i.AuthorID,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSocialBattery = `-- name: UpsertSocialBattery :one
INSERT INTO social_batteries (
  id, level, target_audience, author_id
) VALUES (
  ?, ?, ?, ?
)
ON CONFLICT(target_audience)
DO UPDATE SET 
  level = excluded.level, 
  author_id = excluded.author_id, 
  updated_at = CURRENT_TIMESTAMP
RETURNING id, level, target_audience, author_id, updated_at
`

type UpsertSocialBatteryParams struct {
	ID             string
	Level          int64
	TargetAudience string
	AuthorID       string
}

func (q *Queries) UpsertSocialBattery(ctx context.Context, arg UpsertSocialBatteryParams) (SocialBattery, error) {
	row := q.db.QueryRowContext(ctx, upsertSocialBattery,
		arg.ID,
		arg.Level,
		arg.TargetAudience,
		arg.AuthorID,
	)
	var i SocialBattery
	err := row.Scan(
		&i.ID,
		&i.Level,
		&i.TargetAudience,
		&i.AuthorID,
		&i.UpdatedAt,
	)
	return i, err
}
