version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: gfkit_nginx
    ports:
      - "8081:8081"
    volumes:
      - ./nginx.conf:/etc/nginx/templates/default.conf.template
    network_mode: host
  
